name: Monitor Bundle Build

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'containers/gitops-operator-bundle/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'containers/gitops-operator-bundle/**'


permissions:
  checks: read

jobs:
  wait-for-bundle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for Konflux bundle build to complete
        uses: jitterbit/await-check-suites@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          intervalSeconds: 120        # 2 minutes
          timeoutSeconds: 3600       # 1 hours
          failStepIfUnsuccessful: true

  create-pr:
    if: ${{ github.event_name == 'push' }}  # IMPORTANT: only run on push events
    needs: wait-for-bundle-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo podman

      - name: Generate catalog
        shell: bash
        run: make catalog
      
      - name: Prepare metadata for PR
        id: metadata
        run: |
          BUILD=$(cat BUILD)
          TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
          echo "build=$BUILD" >> $GITHUB_OUTPUT
          echo "ts=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Create Catalog Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: catalog
          commit-message: "chore(nightly): update catalog for build ${{ steps.metadata.outputs.build }}"
          branch: build/catalog-${{ steps.metadata.outputs.build }}-${{ steps.metadata.outputs.ts }}
          delete-branch: true
          title: "chore(nightly): update catalog for build ${{ steps.metadata.outputs.build }}"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          body: |
            This PR updates the catalog using the nightly bundle build.

            Please **do not merge** this PR. It is auto-generated to trigger a catalog build from Konflux.  
            Separate PRs will be created for staging and production bundle updates.

            **Build:** `${{ steps.metadata.outputs.build }}`  
            **Timestamp:** `${{ steps.metadata.outputs.ts }}`

            Automatically generated by GitHub Actions.
          labels: |
            do-not-merge
            nightly